<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Malavika Venugopal">

<title>Market Segmentation Project</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Market_Segmentatiob_files/libs/clipboard/clipboard.min.js"></script>
<script src="Market_Segmentatiob_files/libs/quarto-html/quarto.js"></script>
<script src="Market_Segmentatiob_files/libs/quarto-html/popper.min.js"></script>
<script src="Market_Segmentatiob_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Market_Segmentatiob_files/libs/quarto-html/anchor.min.js"></script>
<link href="Market_Segmentatiob_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Market_Segmentatiob_files/libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Market_Segmentatiob_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Market_Segmentatiob_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Market_Segmentatiob_files/libs/bootstrap/bootstrap-1bc8a17f135ab3d594c857e9f48e611b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Market Segmentation Project</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Malavika Venugopal </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="market-segmentation-project" class="level1">
<h1>Market Segmentation Project</h1>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">1. Introduction</h2>
<p><strong>Market segmentation</strong> is the process of <strong>dividing a broad consumer or business market</strong> into <strong>sub-groups</strong> of consumers based on some shared characteristics.</p>
<section id="purpose" class="level4">
<h4 class="anchored" data-anchor-id="purpose">Purpose</h4>
<ul>
<li><p>Target the right audience</p></li>
<li><p>Improve marketing efficiency</p></li>
<li><p>Increase customer satisfaction</p></li>
<li><p>Boost sales and loyalty</p></li>
</ul>
</section>
</section>
<section id="data-mining" class="level2">
<h2 class="anchored" data-anchor-id="data-mining">2. Data Mining</h2>
<p>We have customer data with these columns:</p>
<ul>
<li><p><strong>Age</strong></p></li>
<li><p><strong>Gender</strong> (1 = female, 0 = male)</p></li>
<li><p><strong>Income</strong></p></li>
<li><p><strong>Married</strong></p></li>
<li><p><strong>Children</strong></p></li>
<li><p><strong>Loan</strong></p></li>
<li><p><strong>Mortgage</strong></p></li>
</ul>
<section id="how-to-segment-this-market" class="level3">
<h3 class="anchored" data-anchor-id="how-to-segment-this-market"><strong>How to Segment This Market :</strong></h3>
<ol type="1">
<li><p><strong>By Age Group</strong> – Young, Middle-aged, Senior</p></li>
<li><p><strong>By Income Level</strong> – Low, Medium, High earners</p></li>
<li><p><strong>By Family Status</strong> – Married vs Unmarried</p></li>
<li><p><strong>By Financial Need</strong> – Has loan/mortgage or not</p></li>
<li><p><strong>By Gender</strong> – Male vs Female</p></li>
</ol>
</section>
<section id="data-exploration" class="level3">
<h3 class="anchored" data-anchor-id="data-exploration">2.1 Data Exploration</h3>
</section>
<section id="introduction-1" class="level3">
<h3 class="anchored" data-anchor-id="introduction-1">2.1.1 Introduction</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>FALSE # A tibble: 30 × 7
FALSE      Age Female Income Married Children  Loan Mortgage
FALSE    &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;
FALSE  1    48      1 17546        0        1     0        0
FALSE  2    40      0 30085.       1        3     1        1
FALSE  3    51      1 16575.       1        0     1        0
FALSE  4    23      1 20375.       1        3     0        0
FALSE  5    57      1 50576.       1        0     0        0
FALSE  6    57      1 37870.       1        2     0        0
FALSE  7    22      0  8877.       0        0     0        0
FALSE  8    58      0 24947.       1        0     1        0
FALSE  9    37      1 25304.       1        2     1        0
FALSE 10    54      0 24212.       1        2     1        0
FALSE # ℹ 20 more rows</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Action the user selections from the Data tab. </span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Build the train/validate/test datasets.</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="co"># nobs=30 train=21 validate=4 test=5</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(crv<span class="sc">$</span>seed)</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>crs<span class="sc">$</span>nobs <span class="ot">&lt;-</span> <span class="fu">nrow</span>(crs<span class="sc">$</span>dataset)</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>crs<span class="sc">$</span>train <span class="ot">&lt;-</span> <span class="fu">sample</span>(crs<span class="sc">$</span>nobs, <span class="fl">0.7</span><span class="sc">*</span>crs<span class="sc">$</span>nobs)</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>crs<span class="sc">$</span>nobs <span class="sc">%&gt;%</span></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">seq_len</span>() <span class="sc">%&gt;%</span></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">setdiff</span>(crs<span class="sc">$</span>train) <span class="sc">%&gt;%</span></span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sample</span>(<span class="fl">0.15</span><span class="sc">*</span>crs<span class="sc">$</span>nobs) <span class="ot">-&gt;</span></span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>crs<span class="sc">$</span>validate</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>crs<span class="sc">$</span>nobs <span class="sc">%&gt;%</span></span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">seq_len</span>() <span class="sc">%&gt;%</span></span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">setdiff</span>(crs<span class="sc">$</span>train) <span class="sc">%&gt;%</span></span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">setdiff</span>(crs<span class="sc">$</span>validate) <span class="ot">-&gt;</span></span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a>crs<span class="sc">$</span>test</span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a><span class="co"># The following variable selections have been noted.</span></span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a>crs<span class="sc">$</span>input     <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Age"</span>, <span class="st">"Female"</span>, <span class="st">"Income"</span>, <span class="st">"Married"</span>,</span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a>                   <span class="st">"Children"</span>, <span class="st">"Loan"</span>, <span class="st">"Mortgage"</span>)</span>
<span id="cb2-29"><a href="#cb2-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-30"><a href="#cb2-30" aria-hidden="true" tabindex="-1"></a>crs<span class="sc">$</span>numeric   <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Age"</span>, <span class="st">"Female"</span>, <span class="st">"Income"</span>, <span class="st">"Married"</span>,</span>
<span id="cb2-31"><a href="#cb2-31" aria-hidden="true" tabindex="-1"></a>                   <span class="st">"Children"</span>, <span class="st">"Loan"</span>, <span class="st">"Mortgage"</span>)</span>
<span id="cb2-32"><a href="#cb2-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-33"><a href="#cb2-33" aria-hidden="true" tabindex="-1"></a>crs<span class="sc">$</span>categoric <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb2-34"><a href="#cb2-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-35"><a href="#cb2-35" aria-hidden="true" tabindex="-1"></a>crs<span class="sc">$</span>target    <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb2-36"><a href="#cb2-36" aria-hidden="true" tabindex="-1"></a>crs<span class="sc">$</span>risk      <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb2-37"><a href="#cb2-37" aria-hidden="true" tabindex="-1"></a>crs<span class="sc">$</span>ident     <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb2-38"><a href="#cb2-38" aria-hidden="true" tabindex="-1"></a>crs<span class="sc">$</span>ignore    <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb2-39"><a href="#cb2-39" aria-hidden="true" tabindex="-1"></a>crs<span class="sc">$</span>weights   <span class="ot">&lt;-</span> <span class="cn">NULL</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="summary" class="level3">
<h3 class="anchored" data-anchor-id="summary">2.1.2 Summary</h3>
<section id="summary-of-training-dataset" class="level4">
<h4 class="anchored" data-anchor-id="summary-of-training-dataset">Summary of Training Dataset</h4>
<p>We analyzed 21 observations across 7 numeric variables from the training set. There are no missing values. Variables include Age, Gender (Female), Income, Marital Status, Children, Loan, and Mortgage. Basic statistics such as minimum, maximum, mean, and quartiles (1st and 3rd) help understand the data spread. For example, 25% of individuals are younger than 37, and 75% are younger than 54. Binary variables like Female, Married, Loan, and Mortgage indicate proportions using means.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>FALSE 
FALSE Data frame:crs$dataset[crs$train, c(crs$input, crs$risk, crs$target)] 21 observations and 7 variables    Maximum # NAs:0
FALSE 
FALSE 
FALSE          Storage
FALSE Age       double
FALSE Female    double
FALSE Income    double
FALSE Married   double
FALSE Children  double
FALSE Loan      double
FALSE Mortgage  double</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>FALSE       Age            Female           Income         Married      
FALSE  Min.   :22.00   Min.   :0.0000   Min.   : 8877   Min.   :0.0000  
FALSE  1st Qu.:37.00   1st Qu.:0.0000   1st Qu.:17546   1st Qu.:1.0000  
FALSE  Median :46.00   Median :1.0000   Median :22523   Median :1.0000  
FALSE  Mean   :45.29   Mean   :0.5714   Mean   :26852   Mean   :0.8095  
FALSE  3rd Qu.:54.00   3rd Qu.:1.0000   3rd Qu.:29359   3rd Qu.:1.0000  
FALSE  Max.   :66.00   Max.   :1.0000   Max.   :59804   Max.   :1.0000  
FALSE     Children           Loan           Mortgage     
FALSE  Min.   :0.0000   Min.   :0.0000   Min.   :0.0000  
FALSE  1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.0000  
FALSE  Median :1.0000   Median :0.0000   Median :0.0000  
FALSE  Mean   :0.9524   Mean   :0.3333   Mean   :0.3333  
FALSE  3rd Qu.:2.0000   3rd Qu.:1.0000   3rd Qu.:1.0000  
FALSE  Max.   :3.0000   Max.   :1.0000   Max.   :1.0000</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>FALSE $Age
FALSE                X...X.i
FALSE nobs         21.000000
FALSE NAs           0.000000
FALSE Minimum      22.000000
FALSE Maximum      66.000000
FALSE 1. Quartile  37.000000
FALSE 3. Quartile  54.000000
FALSE Mean         45.285714
FALSE Median       46.000000
FALSE Sum         951.000000
FALSE SE Mean       3.002493
FALSE LCL Mean     39.022623
FALSE UCL Mean     51.548806
FALSE Variance    189.314286
FALSE Stdev        13.759153
FALSE Skewness     -0.216740
FALSE Kurtosis     -1.094729
FALSE 
FALSE $Female
FALSE               X...X.i
FALSE nobs        21.000000
FALSE NAs          0.000000
FALSE Minimum      0.000000
FALSE Maximum      1.000000
FALSE 1. Quartile  0.000000
FALSE 3. Quartile  1.000000
FALSE Mean         0.571429
FALSE Median       1.000000
FALSE Sum         12.000000
FALSE SE Mean      0.110657
FALSE LCL Mean     0.340603
FALSE UCL Mean     0.802254
FALSE Variance     0.257143
FALSE Stdev        0.507093
FALSE Skewness    -0.268303
FALSE Kurtosis    -2.017385
FALSE 
FALSE $Income
FALSE                   X...X.i
FALSE nobs         2.100000e+01
FALSE NAs          0.000000e+00
FALSE Minimum      8.877070e+03
FALSE Maximum      5.980390e+04
FALSE 1. Quartile  1.754600e+04
FALSE 3. Quartile  2.935910e+04
FALSE Mean         2.685174e+04
FALSE Median       2.252280e+04
FALSE Sum          5.638865e+05
FALSE SE Mean      3.083299e+03
FALSE LCL Mean     2.042009e+04
FALSE UCL Mean     3.328339e+04
FALSE Variance     1.996414e+08
FALSE Stdev        1.412945e+04
FALSE Skewness     1.038500e+00
FALSE Kurtosis    -1.272220e-01
FALSE 
FALSE $Married
FALSE               X...X.i
FALSE nobs        21.000000
FALSE NAs          0.000000
FALSE Minimum      0.000000
FALSE Maximum      1.000000
FALSE 1. Quartile  1.000000
FALSE 3. Quartile  1.000000
FALSE Mean         0.809524
FALSE Median       1.000000
FALSE Sum         17.000000
FALSE SE Mean      0.087805
FALSE LCL Mean     0.626365
FALSE UCL Mean     0.992682
FALSE Variance     0.161905
FALSE Stdev        0.402374
FALSE Skewness    -1.465227
FALSE Kurtosis     0.161265
FALSE 
FALSE $Children
FALSE               X...X.i
FALSE nobs        21.000000
FALSE NAs          0.000000
FALSE Minimum      0.000000
FALSE Maximum      3.000000
FALSE 1. Quartile  0.000000
FALSE 3. Quartile  2.000000
FALSE Mean         0.952381
FALSE Median       1.000000
FALSE Sum         20.000000
FALSE SE Mean      0.233770
FALSE LCL Mean     0.464745
FALSE UCL Mean     1.440017
FALSE Variance     1.147619
FALSE Stdev        1.071270
FALSE Skewness     0.553157
FALSE Kurtosis    -1.213590
FALSE 
FALSE $Loan
FALSE               X...X.i
FALSE nobs        21.000000
FALSE NAs          0.000000
FALSE Minimum      0.000000
FALSE Maximum      1.000000
FALSE 1. Quartile  0.000000
FALSE 3. Quartile  1.000000
FALSE Mean         0.333333
FALSE Median       0.000000
FALSE Sum          7.000000
FALSE SE Mean      0.105409
FALSE LCL Mean     0.113453
FALSE UCL Mean     0.553213
FALSE Variance     0.233333
FALSE Stdev        0.483046
FALSE Skewness     0.657205
FALSE Kurtosis    -1.639456
FALSE 
FALSE $Mortgage
FALSE               X...X.i
FALSE nobs        21.000000
FALSE NAs          0.000000
FALSE Minimum      0.000000
FALSE Maximum      1.000000
FALSE 1. Quartile  0.000000
FALSE 3. Quartile  1.000000
FALSE Mean         0.333333
FALSE Median       0.000000
FALSE Sum          7.000000
FALSE SE Mean      0.105409
FALSE LCL Mean     0.113453
FALSE UCL Mean     0.553213
FALSE Variance     0.233333
FALSE Stdev        0.483046
FALSE Skewness     0.657205
FALSE Kurtosis    -1.639456</code></pre>
</div>
</div>
</section>
</section>
<section id="detailed-summary-of-individual-variables" class="level3">
<h3 class="anchored" data-anchor-id="detailed-summary-of-individual-variables">2.1.3 <strong>Detailed Summary of Individual Variables</strong></h3>
<section id="age" class="level4">
<h4 class="anchored" data-anchor-id="age">2.1.3.1. Age</h4>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>FALSE Warning: The `fun.y` argument of `stat_summary()` is deprecated as of ggplot2 3.3.0.
FALSE ℹ Please use the `fun` argument instead.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Market_Segmentatiob_files/figure-html/Box%20Plot%20of%20Age-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Box Plot of Age</strong></p>
<p>The box plot of the <code>Age</code> variable shows the <strong>distribution of ages</strong> in the training dataset. The <strong>median age is 46</strong>, and the <strong>interquartile range (IQR)</strong> lies between <strong>37 (Q1)</strong> and <strong>54 (Q3)</strong>. This means that the middle 50% of individuals are between 37 and 54 years old.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Market_Segmentatiob_files/figure-html/Histogram%20of%20Age-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Histogram of Age</strong></p>
<p>The histogram of <code>Age</code> shows the <strong>distribution of ages</strong> in the dataset. Most individuals are between <strong>35 and 55 years old</strong>, indicating a concentration in the middle-age range. The distribution appears roughly <strong>symmetric</strong>, with no extreme outliers, suggesting a <strong>balanced age profile</strong> in the sample.</p>
</section>
<section id="female" class="level4">
<h4 class="anchored" data-anchor-id="female">2.1.3.2 Female</h4>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>FALSE crs$dataset$Female 
FALSE        n  missing distinct     Info      Sum     Mean 
FALSE       30        0        2    0.737       17   0.5667</code></pre>
</div>
</div>
<p>The <code>Female</code> variable represents gender in binary form, where <code>1</code> indicates <strong>Female</strong> and <code>0</code> indicates <strong>Male</strong>. Out of 30 total observations, <strong>17 are Female</strong>, making up <strong>56.67%</strong> of the dataset.</p>
</section>
<section id="income" class="level4">
<h4 class="anchored" data-anchor-id="income">2.1.3.3. Income</h4>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Market_Segmentatiob_files/figure-html/Box%20Plot%20of%20Income-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Box Plot of Income</strong></p>
<p>The box plot of <code>Income</code> displays the <strong>spread and distribution</strong> of income values in the dataset. The <strong>median income</strong> is around ₹22,523, with the <strong>interquartile range (IQR)</strong> spanning from ₹17,546 (Q1) to ₹29,359 (Q3). The plot also shows a <strong>right-skewed distribution</strong>, with some individuals having significantly higher incomes, indicating the presence of <strong>outliers or high earners</strong> in the sample.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Market_Segmentatiob_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Histogram of Income</strong></p>
<p>The histogram of <code>Income</code> shows a <strong>right-skewed distribution</strong>, where most individuals earn between <strong>₹10,000 and ₹30,000</strong>. A few observations fall in the higher income range, indicating the presence of <strong>high-income outliers</strong>. This suggests that income levels vary widely across the sample, with a concentration of individuals in the <strong>lower-to-middle income range</strong>.</p>
</section>
<section id="married" class="level4">
<h4 class="anchored" data-anchor-id="married">2.1.3.4. Married</h4>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>FALSE crs$dataset$Married 
FALSE        n  missing distinct     Info      Sum     Mean 
FALSE       30        0        2    0.481       24      0.8</code></pre>
</div>
</div>
<p>The <code>Married</code> variable indicates marital status in binary form, where <code>1</code> denotes <strong>Married</strong> and <code>0</code> denotes <strong>Unmarried</strong>. Out of 30 observations, <strong>24 are Married</strong>, which accounts for <strong>80%</strong> of the dataset.</p>
</section>
<section id="children" class="level4">
<h4 class="anchored" data-anchor-id="children">2.1.3.5. Children</h4>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Market_Segmentatiob_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Box Plot of Children</strong><br>
<br>
The box plot of <code>Children</code> reveals a <strong>median of 1</strong>, with most values ranging between <strong>0 and 2</strong>. There are <strong>no extreme outliers</strong>, and the data indicates <strong>small family sizes</strong>.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Market_Segmentatiob_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Histogram of Children</strong></p>
<p>The histogram shows that having <strong>0, 1, or 2 children</strong> is most common in the dataset. The <strong>highest frequency is at 1 child</strong>, reflecting a trend toward <strong>smaller households</strong>.</p>
</section>
<section id="loan" class="level4">
<h4 class="anchored" data-anchor-id="loan">2.1.3.6. Loan</h4>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>FALSE crs$dataset$Loan 
FALSE        n  missing distinct     Info      Sum     Mean 
FALSE       30        0        2    0.737       13   0.4333</code></pre>
</div>
</div>
<p>The <code>Loan</code> variable indicates whether a loan was <strong>approved (1)</strong> or <strong>not approved (0)</strong>. Out of 30 total records, <strong>13 have loans approved</strong>, which is <strong>43.33%</strong> of the dataset. This suggests that <strong>less than half</strong> of the individuals in the dataset received a loan.</p>
</section>
<section id="mortgage" class="level4">
<h4 class="anchored" data-anchor-id="mortgage">2.1.3.7. Mortgage</h4>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>FALSE crs$dataset$Mortgage 
FALSE        n  missing distinct     Info      Sum     Mean 
FALSE       30        0        2    0.721       12      0.4</code></pre>
</div>
</div>
<p>The <code>Mortgage</code> variable represents whether a person <strong>has a mortgage (1)</strong> or <strong>does not have one (0)</strong>. Out of <strong>30 individuals</strong>, <strong>12 people</strong> have a mortgage, which is <strong>40%</strong> of the dataset. This indicates that <strong>less than half</strong> of the individuals in the dataset have taken a mortgage.</p>
</section>
</section>
<section id="clustering-analysis-of-demoktc-dataset-using-manhattan-and-canberra-distance-methods" class="level3">
<h3 class="anchored" data-anchor-id="clustering-analysis-of-demoktc-dataset-using-manhattan-and-canberra-distance-methods">2.1.4 Clustering Analysis of DemoKTC Dataset Using Manhattan and Canberra Distance Methods</h3>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Market_Segmentatiob_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Market_Segmentatiob_files/figure-html/unnamed-chunk-13-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Market_Segmentatiob_files/figure-html/unnamed-chunk-13-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>FALSE Warning in data2$cluster &lt;- km$cluster: Coercing LHS to a list</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>FALSE  [1] 1 2 2 2 3 3 1 3 2 2 3 1 2 3 2 2 2 3 3 2 3 2 3 1 1 3 2 2 1 3</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>FALSE [1] "9 15 6"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>FALSE       Age    Female    Income   Married  Children      Loan  Mortgage 
FALSE 0.5446970 0.5666667 0.3757313 0.8000000 0.3111111 0.4333333 0.4000000</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>FALSE         Age    Female    Income Married  Children      Loan Mortgage
FALSE 1 0.5303030 0.5555556 0.4004398       1 0.2592593 0.4444444      1.0
FALSE 2 0.6530303 0.5333333 0.4361136       1 0.3333333 0.3333333      0.0
FALSE 3 0.2954545 0.6666667 0.1877126       0 0.3333333 0.6666667      0.5</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>FALSE [1]  6.481327 11.117786  5.631834</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Market_Segmentatiob_files/figure-html/unnamed-chunk-13-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>FALSE   cluster_id      Age    Female   Income Married  Children      Loan  Mortgage
FALSE 1          1 35.00000 0.6666667 18436.68       0 1.0000000 0.6666667 0.5000000
FALSE 2          2 40.38462 0.5384615 20906.03       1 1.2307692 0.4615385 0.4615385
FALSE 3          3 58.54545 0.5454545 41632.52       1 0.5454545 0.2727273 0.2727273</code></pre>
</div>
</div>
<section id="cluster-profiling-summary" class="level4">
<h4 class="anchored" data-anchor-id="cluster-profiling-summary"><strong>Cluster Profiling Summary:</strong></h4>
<ul>
<li><p><strong>Cluster 1:</strong> Lower values on most variables – possibly conservative or cost-sensitive group.</p></li>
<li><p><strong>Cluster 2:</strong> High on variable 3 and 4 – possibly tech-savvy or performance-focused.</p></li>
<li><p><strong>Cluster 3:</strong> High on variable 2, lower on variable 3 – likely a balanced preference group.</p></li>
</ul>
</section>
</section>
</section>
<section id="insights-and-discussion" class="level2">
<h2 class="anchored" data-anchor-id="insights-and-discussion">3. Insights and Discussion</h2>
<p>The analysis reveals that the dataset is dominated by middle-aged individuals, mostly in the range of 35 to 55 years. This indicates that marketing messages emphasizing stability, financial planning, and family security may resonate well with the majority. The income distribution, which is skewed towards the lower to middle range, but with the presence of high-income outliers, suggests that there is room for dual strategies: affordable and value-based offerings for the majority, and premium products for the smaller high-income group. The overwhelming proportion of married individuals indicates that family-oriented offerings, such as family insurance packages, bundled services, or family-centric promotions, could be highly effective. With about 40 to 45 percent of individuals having loans or mortgages, cross-selling financial services and debt management products becomes a strong opportunity.</p>
<p>The cluster analysis strengthens these insights by showing that customers fall broadly into three categories: conservative low spenders, financially active families, and independent professionals. Each of these groups presents unique needs, and tailoring marketing strategies accordingly can significantly improve efficiency and effectiveness.</p>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">4. Conclusion</h2>
<p>This project demonstrates how market segmentation can be applied using demographic and financial data. The combination of descriptive analysis and clustering reveals three meaningful customer segments, each with distinct characteristics and needs. Businesses that adapt their marketing strategies to these groups can expect better customer targeting, improved satisfaction, and stronger sales growth. In summary, segmentation has proven to be a powerful tool for understanding consumer diversity and aligning business strategies with customer needs.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>